# Generated by Django 3.2.7 on 2021-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_news_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='non_empty',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
