# Generated by Django 3.2.8 on 2021-10-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
